sdcard.exe: main.obj sd.obj sdcmds.obj helpers.obj fat32.obj
    tcc -ms -eISASD.EXE main.obj sdcmds.obj helpers.obj fat32.obj sd.c

sdcmds.obj: sdcmds.asm
    tasm /mx sdcmds.asm

helpers.obj: helpers.c
    tcc -ms -c helpers.c

fat32.obj: fat32.c fat32.h partn.h
    tcc -ms -c fat32.c

main.obj: main.c
    tcc -ms -c main.c

sd.obj: sd.c
    tcc -ms -c sd.c

clean:
    del *.obj
